name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        perl-version: ['5.26', '5.28', '5.30']
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: local
          key: local-${{ runner.os }}-${{ matrix.perl-version }}-${{ hashFiles('cpanfile') }}
          restore-keys: |
            local-${{ runner.os }}-${{ matrix.perl-version }}-

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Remove Perl Problem Matcher
        run: echo "::remove-matcher owner=perl::"

      - run: cpanm -L local --installdeps .

      - run: prove -Ilocal/lib/perl5 -Ilib -lv t
