name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        perl-version: 
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: local
          key: local-${{ runner.os }}-${{ matrix.perl-version }}-${{ hashFiles('cpanfile') }}
          restore-keys: |
            local-${{ runner.os }}-${{ matrix.perl-version }}-

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Remove Perl Problem Matcher
        run: echo "::remove-matcher owner=perl::"

      - run: cpanm -L local --installdeps .

      - run: cpanm -L local Test2::Plugin::GitHub::Actions::AnnotateFailedTest

      - run: prove -Ilocal/lib/perl5 -Ilib -lv t

  critic:
    env:
      perl-version: '5.32'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: local
          key: local-${{ runner.os }}-${{ env.perl-version }}-with-develop-${{ hashFiles('cpanfile') }}
          restore-keys: |
            local-${{ runner.os }}-${{ env.perl-version }}-
            local-${{ runner.os }}-${{ env.perl-version }}-with-develop-

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ env.perl-version }}

      - run: cpanm -L local --with-develop --installdeps .

      - uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          perl -Ilocal/lib/perl5 ./local/bin/perlcritic --profile .perlcriticrc --verbose '%f:%l:%c:**%m**, near <code>%r</code>.<br>(Ref: [%p](https://metacpan.org/pod/Perl::Critic::Policy::%p))\n' lib t | reviewdog -efm=%f:%l:%c:%m -name=perlcritic -reporter=github-pr-review
