name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        perl-version: 
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          install-modules-with: cpanm
          install-modules: Test2::Plugin::GitHub::Actions::AnnotateFailedTest

      - name: Remove Perl Problem Matcher
        run: echo "::remove-matcher owner=perl::"

      - run: prove -Ilib -lv t

  critic:
    env:
      perl-version: '5.32'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ env.perl-version }}
          install-modules-with: cpanm
          install-modules-args: --with-develop

      - uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          perlcritic --profile .perlcriticrc --verbose '%f:%l:%c:**%m**, near <code>%r</code>.<br>(Ref: [%p](https://metacpan.org/pod/Perl::Critic::Policy::%p))\n' lib t | reviewdog -efm=%f:%l:%c:%m -name=perlcritic -reporter=github-pr-review
